# SamSkyBridge 기본 설정
lang: ko
save-interval-ticks: 1200
rank-refresh-interval-ticks: 1200

economy:
  enabled: true
  costs:
    size:
      base: 10000
      multiplier: 1.25
      level-required-base: 5
      level-required-step: 2   # 반지름 10씩 늘 때마다 +2레벨 요구
    team:
      base: 5000
      multiplier: 1.5
      level-required-base: 3
      level-required-step: 1

leveling:
  base-required-xp: 1000
  increase-percent: 1.5     # 다음 레벨 필요치 +1.5%
  track-placements: true

barrier:
  show-seconds: 6
  step: 2.0
  particle-per-block: false

scoreboard:
  prefix-format: "&7[ &a섬 랭킹 &f<rank>위 &7] "

gui:
  title-upgrade: "섬 업그레이드"
  size-item-name: "&f섬 크기 업그레이드"
  team-item-name: "&f팀원 수 업그레이드"
  back-item-name: "&7닫기"

storage:
  data-file: "data/islands.yml"


integration:
  bentobox:
    enabled: true
    gamemode-id: "bskyblock"   # 'acidisland', 'boxed' 등 서버 환경에 맞게
